server:
  port: 8085
spring:
  dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181
      ##dubbo协议的端口号
    protocol:
      port: 29014
    scan: com.nfsq.yqf.dubboprovider.biz
